// <auto-generated />
using System;
using CSM.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSM.Persistence.Migrations
{
    [DbContext(typeof(CsmDbContext))]
    [Migration("20250924224349_NullableFieldsToAlerta")]
    partial class NullableFieldsToAlerta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CSM.Domain.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NivelMacd")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NivelRsi")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NivelVolume")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrecoAlvo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("tbAlerta", (string)null);
                });

            modelBuilder.Entity("CSM.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Perfil")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramChatId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tbUsuario", (string)null);
                });

            modelBuilder.Entity("CSM.Domain.Alerta", b =>
                {
                    b.HasOne("CSM.Domain.Usuario", "Usuario")
                        .WithMany("Alertas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CSM.Domain.Usuario", b =>
                {
                    b.Navigation("Alertas");
                });
#pragma warning restore 612, 618
        }
    }
}
